name: Terraform Module Build
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:

env:
  ARM_CLIENT_ID: '2c7dadc2-5dba-4670-b798-27d59a430217'
  ARM_CLIENT_SECRET: ${{ secrets.TGO_ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: 'e5c064d7-9c8f-4e8d-ba57-5da9f1610cb3'
  ARM_TENANT_ID: 'ea7c73d0-fb18-4161-8331-8341717ba99c'
  TF_CLI_VERSION: '1.0.9'

jobs:
  # tflint:
  terrascan:
    runs-on: ubuntu-latest
    name: terrascan-action
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      # https://github.com/marketplace/actions/terrascan-iac-scanner
    - name: Run Terrascan
      id: terrascan
      uses: accurics/terrascan-action@main
      with:
        iac_type: 'terraform'
        iac_version: 'v14'
        policy_type: 'azure'
        only_warn: true
        verbose: true
        sarif_upload: true
        #non_recursive:
        iac_dir: /
        #policy_path:
        #skip_rules:
        #config_path:
        #find_vulnerabilities:
    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: terrascan.sarif

  terratest_job:
    runs-on: ubuntu-latest
    name: terratest-action
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - uses: hashicorp/setup-terraform@v1
      with:
        terraform_wrapper: false
        terraform_version: ${{ env.TF_CLI_VERSION }}

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Setup Dependencies
      working-directory: tests
      #run:  go get -v -t -d && go mod tidy
      run: go mod init tests

    - name: Test
      working-directory: tests
      run: |
        echo "TF_VAR_gh_run_id: ${GITHUB_RUN_ID}"
        echo "TF_VAR_gh_repo: ${TF_VAR_gh_repo}"
        go test -v
      env:
        TF_VAR_gh_run_id: ${{ env.GITHUB_RUN_ID }}
        TF_VAR_gh_repo: ${{ env.GITHUB_REPOSITORY }}

    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v5.6
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    - name: Create a GitHub release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ steps.tag_version.outputs.new_tag }}
        name: Release ${{ steps.tag_version.outputs.new_tag }}
        body: ${{ steps.tag_version.outputs.changelog }}
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'

  # tag_repo:
